include:
  - https://auto-version-tag-ci.fluxlabs.ch/auto_version_tag_ci.yml

variables:
  DOCKER_REGISTRY_NAME: flux-auto-version-tag-ci
  DEV_DOCKER_REGISTRY_IMAGE: $DEV_DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_NAME
  DOCKER_REGISTRY_IMAGE: $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_NAME

build:
  stage: build
  script:
    - echo -n $DEV_DOCKER_REGISTRY_PASSWORD | docker login -u $DEV_DOCKER_REGISTRY_USER --password-stdin $DEV_DOCKER_REGISTRY_URL;
      docker build . --pull -t $DEV_DOCKER_REGISTRY_IMAGE:latest;
      docker push $DEV_DOCKER_REGISTRY_IMAGE:latest;
      docker logout $DEV_DOCKER_REGISTRY_URL;
  only:
    - /^develop$/

publish:
  stage: deploy
  script:
    - echo -n $DEV_DOCKER_REGISTRY_PASSWORD | docker login -u $DEV_DOCKER_REGISTRY_USER --password-stdin $DEV_DOCKER_REGISTRY_URL;
      docker pull $DEV_DOCKER_REGISTRY_IMAGE:latest;
      docker logout $DEV_DOCKER_REGISTRY_URL;
    - echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URL;
      docker tag $DEV_DOCKER_REGISTRY_IMAGE:latest $DOCKER_REGISTRY_IMAGE:latest;
      docker push $DOCKER_REGISTRY_IMAGE:latest;
      docker logout $DOCKER_REGISTRY_URL;
  only:
    - /^master$/
