include:
  - https://plugins.studer-raimann.ch/Customizing/global/auto_version_tag_ci/build/auto_version_tag_ci.yml
  - https://plugins.studer-raimann.ch/Customizing/global/auto_version_tag_ci/build/docker_build.yml
